### ISSUE TITLE
/binding Issues

### ISSUE THREAD

**Issue by v1ckych3n** [lucykim0921/binding#1]
Hi Lucy, here are some issues that I found on /binding.
- [ ] For lines 21 to 40, I don't know the exact rule about heading order but `<h2>Overview: <nobr>Breaking Boundaries</nobr></h2>` was placed after `<section class="overview"> <h3>DESIGN MANIFESTO</h3>`. If having a lower h3 before h2, I don't know if that will affect the robot reader's hierarchy in HTML. If it's for styling, maybe add a class or ID that is specifically for the styling usage. 
- [ ] I got confused when trying to navigate the CSS style guide that you using as the main styling file. I assumed that common.css was the the main stylesheet but it wasn't? Maybe move your final style direction into the common.css file since we are not doing the three directional files anymore. 
- [ ] Suggestion: maybe you can add your font files into your main CSS stylesheet in case other people's computer doesn't have the same font as yours. You can use @import<link> if you are using Google Fonts or @fontface {} for local font files which you can make a fonts folder that's part of your repository and link it to @fontface. 
- [ ] Iskander.html = <div class="Iskander_header">, you can use a <header> Semantic DOM to help clarify the code structure.
- [ ] Iskander.html = I saw that from line 32 to 44 that there is a lot of class inputs for the <div>. Maybe you can target all the <div> that's underneath the .divider_section by doing the descending target thing like this .divider_section > div {}.
```css
.divider_section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-direction: row;
  margin-bottom: 50px;
}

.divider_section > div {
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background-color: #3498db; 

  &:nth-child(odd) {
    border-radius: 0;
    background-color: #e74c3c; 
  }
}
``` 
Let me know if there is anything I can clarify on!
